name: Setup Node.js and Pnpm
description: Setup Node.js and Pnpm Action

runs:
  using: composite
  steps:
    - name: Use Node.js
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        node-version-file: ./.node-version

    - name: Check Node.js version
      shell: bash
      run: node --version

    - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      name: Install pnpm
      with:
        run_install: false

    - name: Check pnpm version
      shell: bash
      run: pnpm --version

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      name: Setup pnpm cache
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/.node-version') }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-node-${{ hashFiles('**/.node-version') }}-pnpm-store-
