name: Setup Node.js and Pnpm
description: Setup Node.js and Pnpm Action

runs:
  using: composite
  steps:
    - name: Use Node.js
      uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
      with:
        node-version-file: ./.node-version

    - name: Check Node.js version
      shell: bash
      run: node --version

    - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      name: Install pnpm
      with:
        run_install: false

    - name: Check pnpm version
      shell: bash
      run: pnpm --version

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
      name: Setup pnpm cache
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/.node-version') }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-node-${{ hashFiles('**/.node-version') }}-pnpm-store-
