name: 機能要望
description: 新機能や改善の要望を記載するテンプレート
title: "[要望] "
labels: []
body:
  - type: textarea
    id: background
    attributes:
      label: 背景・目的
      description: この要望を出すに至った背景や目的を記載してください
      placeholder: 例: ユーザーが〇〇をしたい時に、現在は△△という手順が必要で不便に感じているため...
    validations:
      required: true

  - type: textarea
    id: requirements
    attributes:
      label: 要件・要望の詳細
      description: 実現したい機能や改善内容を具体的に記載してください
      placeholder: |
        例:
        - 〇〇ができるようにする
        - △△の操作を簡略化する
        - ××の情報を表示する
    validations:
      required: true

  - type: textarea
    id: figma
    attributes:
      label: Figmaデザイン
      description: Figmaで作成したデザインのリンクを記載してください
      placeholder: https://www.figma.com/file/...

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: 受け入れ基準
      description: この要望が完了したと判断する基準を記載してください（任意）
      placeholder: |
        例:
        - [ ] 〇〇が動作すること
        - [ ] △△のテストが通ること
